# 171120 NumPy & Pandas 입문

### 1) NumPy

In [1]:
import numpy

arr1 = numpy.array([1,2,3]) #1차원
arr1

array([1, 2, 3])

In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
arr2 = numpy.array([[1,2,3],[4,5,6]]) #다차원
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
numpy.arange(10) #데이터 타입 : int

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
numpy.arange(10, dtype='float64')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [6]:
 numpy.arange(10.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [7]:
numpy.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
numpy.arange(3,10,2,dtype='float64')

array([ 3.,  5.,  7.,  9.])

In [9]:
numpy.arange(3,10,-3)

array([], dtype=int64)

In [10]:
numpy.arange(10,3,-3)

array([10,  7,  4])

In [11]:
#모든 값이 0인 2x2 배열 생성
numpy.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [12]:
#모든 값이 1인 1x2 배열 생성
numpy.ones((1,2))

array([[ 1.,  1.]])

In [13]:
#모든 값이 특정 상수인 1x2 배열 생성
numpy.full((1,2),10)

array([[10, 10]])

In [14]:
#단위행렬 생성
numpy.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
numpy.eye(3, k=1) #k=1만큼 이동 / 양수는 우측으로 올라감.

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [16]:
numpy.eye(3, k=-2) #k=-2만큼 이동 / 음수는 좌측으로 내려감.

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [17]:
#랜덤한 값으로 채워진 2x2 배열 생성
numpy.random.random((2,2))

array([[ 0.50511835,  0.28022338],
       [ 0.6738009 ,  0.23081364]])

### numpy.diag
정사각 행렬의 대각/비대각 원소를 1차원으로 배열로 반환하거나 1차원 배열을 대각선 원소로 하고, 나머지는 0으로 채운 단위 행렬을 반환한다.

In [18]:
arr = numpy.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
numpy.diag(arr)

array([ 0,  5, 10])

In [20]:
numpy.diag(arr, k=1)

array([ 1,  6, 11])

In [21]:
numpy.diag(arr, k=-1)

array([4, 9])

In [22]:
numpy.diag([1,5,10])

array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 10]])

In [23]:
numpy.diag([1,5,10],k=-1)

array([[ 0,  0,  0,  0],
       [ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0]])

### 배열의 Rank와 Shape

#### 1) Rank(ndim) : 배열이 몇 차원인지를 의미

In [24]:
arr1=numpy.array([1,2,3])
arr1.ndim

1

In [29]:
arr2=numpy.array([[1,2,3],[4,5,6]])
arr2.ndim

2

In [30]:
arr3=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3.ndim

3

#### 2) Shape : 각 차원의 크기를 알려주는 튜플

In [31]:
arr1=numpy.array([1,2,3])
arr1.shape

(3,)

In [32]:
arr2=numpy.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

In [33]:
arr3=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3.shape

(2, 2, 3)

In [38]:
arr4=numpy.array([1,2,3,4,5,6])
print(arr4.ndim) #1차원 array / rank는 [] 갯수
print(arr4.shape) #6개

1
(6,)


In [40]:
arr5=numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr5.ndim) #2차원 array / rank는 [] 갯수
print(arr5.shape) #[]가 4개, []안에 3개씩 => (4,3)

2
(4, 3)


In [41]:
arr6=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr6.ndim) #3차원 array / rank는 [] 갯수
print(arr6.shape) #

3
(2, 2, 3)



### 배열 인덱싱
#### 1)배열 분할(slicing)

In [42]:
arr1 = numpy.array([1,2,3])
arr1[0]

1

In [43]:
arr2 = numpy.array([[1,2,3],[4,5,6]])
arr2[1]

array([4, 5, 6])

In [44]:
arr3 = numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0][1]

array([4, 5, 6])

In [45]:
arr3[0,0,1]

2

In [46]:
arr4 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr5 = arr4[:2,:] 
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 2) Boolean 배열 인덱싱
- 특정 조건을 만족하는 요소는 True, 만족하지 않는 요소는 False로 반환.
- 이를 통해 특정 조건을 만족하는 원소들만 취사선택해 배열로 저장할 수 있음

In [48]:
arr = numpy.array([[1,2],[3,4],[5,6]])
bidx = arr > 3
bidx

array([[False, False],
       [False,  True],
       [ True,  True]], dtype=bool)

In [49]:
arr[bidx]

array([4, 5, 6])

### 배열 자료형

int64(정수형), float64(실수형)

In [50]:
arr1 = numpy.array([1])
arr1.dtype, arr1.dtype.name

(dtype('int64'), 'int64')

In [51]:
arr2 = numpy.array([1.0])
arr2.dtype

dtype('float64')

In [53]:
#배열을 생성할 때 명시적으로 특정 자료형을 지정할 수 있음
arr3 = numpy.array([1,2], dtype = numpy.float64)
arr3.dtype.name

'float64'

### 배열 연산 

In [54]:
arr1 = numpy.array([[1,2], [3,4]], dtype = numpy.float64)
arr2 = numpy.array([[5,6], [7,8]], dtype = numpy.float64)

In [55]:
arr1 + arr2 #첫번째(n11) 자릿값 = 1+5 = 6

array([[  6.,   8.],
       [ 10.,  12.]])

In [56]:
arr1 - arr2 #첫번째(n11) 자릿값 = 1-5 = -4

array([[-4., -4.],
       [-4., -4.]])

In [57]:
arr1 * arr2 #행렬의 곱연산이 아님 / 첫번째(n11) 자릿값 = 1x5 = 5

array([[  5.,  12.],
       [ 21.,  32.]])

In [58]:
arr1 / arr2 #첫번째(n11) 자릿값 = 1/5 = 0.2

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [59]:
numpy.sqrt(arr1)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

#### 내적 및 행렬의 곱연산 - numpy.dot

In [60]:
#벡터의 내적
vector1 = numpy.array([1,2])
vector2 = numpy.array([3,4])

numpy.dot(vector1, vector2) #1*3+2*4

11

In [61]:
# 행렬의 곱연산
arr1 = numpy.array([[1,2], [3,4]], dtype = numpy.float64)
arr2 = numpy.array([[5,6], [7,8]], dtype = numpy.float64)

numpy.dot(arr1, arr2)

array([[ 19.,  22.],
       [ 43.,  50.]])

#### 배열의 합연산 - numpy.sum

In [62]:
arr = numpy.array([[1,2], [3,4],[5,6]], dtype = numpy.float64)
numpy.sum(arr) #1+2+3+4+5+6

21.0

In [63]:
numpy.sum(arr,axis=0) #axis=0 : 열에 대해 합(세로로) / 1+3+5

array([  9.,  12.])

In [64]:
numpy.sum(arr,axis=1) #axis=1 : 행에 대해 합(가로로) / 1+2

array([  3.,   7.,  11.])

In [65]:
arr = numpy.array([[1,2], [3,4],[5,6]], dtype = numpy.float64)
arr

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [66]:
arr.T #행과 열을 바꿈

array([[ 1.,  3.,  5.],
       [ 2.,  4.,  6.]])

### 배열의 Reshape
데이터의 변화 없이 새로운 차원의 배열로 변환

In [67]:
arr = numpy.arange(10).reshape(5,2)
arr #5x2배열

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
#reshape를 이용해서 2x5 배열로 변환.
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
#reshape를 이용해서 5x2 배열로 변환.
numpy.reshape(arr,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
#행과 열을 바꾸고 싶으면
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [79]:
arr = numpy.reshape(arr,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#배열을 1xn으로 만들고 싶을 때
numpy.reshape(arr,(1,-1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
#배열을 nx1으로 만들고 싶을 때
numpy.reshape(arr,(-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
#배열을 5xn으로 만들고 싶을 때
numpy.reshape(arr,(5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
#배열을 nx5으로 만들고 싶을 때 
numpy.reshape(arr,(-1,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 데이터 호출

#### 1)수치형 데이터 불러오기
loadtxt

In [84]:
data = numpy.loadtxt('data/test-data.csv',delimiter = ',')
data

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.],
       [  69.,   74.,   77.,  149.],
       [  47.,   56.,   60.,  115.],
       [  87.,   79.,   90.,  175.],
       [  79.,   70.,   88.,  164.],
       [  69.,   70.,   73.,  141.],
       [  70.,   65.,   74.,  141.],
       [  93.,   95.,   91.,  184.],
       [  79.,   80.,   73.,  152.],
       [  70.,   73.,   78.,  148.],
       [  93.,   89.,   96.,  192.],
       [  78.,   75.,   68.,  147.],
       [  81.,   90.,   93.,  183.],
       [  88.,   92.,   86.,  177.],
       [  78.,   83.,   77.,  159.],
       [  82.,   86.,   90.,  177.],
       [  86.,   82.,   89.,  175.],
       [  78.,   83.,   85.,  175.],
       [  76.,   83.,   71.,  149.],
       [  96.,   93.,   95.,  192.]])

#### 2) 수치형 및 문자열 데이터 불러오기
genfromtxt()

In [85]:
data = numpy.genfromtxt('data/building.csv',dtype=None, delimiter = ',')
data

array([[b'building', b'city', b'height'],
       [b'Empire State Building', b'New York', b'381'],
       [b'Eiffel Tower', b'Paris', b'300'],
       [b'63 building', b'Seoul', b'250']], 
      dtype='|S21')

## 171121 Numpy 실습

### 실습 2-1 랜덤 벡터 생성과 정렬

길이 10인 랜덤 벡터(1차원 배열)을 생성하고 이를 정렬
오름차순과 내림차순으로 한 번씩 정렬

In [1]:
import numpy
arr = numpy.random.random(10)
arr

array([ 0.42606694,  0.90699913,  0.12953234,  0.49654601,  0.26652212,
        0.00316708,  0.9560996 ,  0.61399681,  0.4142223 ,  0.82006522])

In [2]:
arr.sort() #오름차순
arr

array([ 0.00316708,  0.12953234,  0.26652212,  0.4142223 ,  0.42606694,
        0.49654601,  0.61399681,  0.82006522,  0.90699913,  0.9560996 ])

In [3]:
arr[::-1].sort() #내림차순 / [::-1] 자체가 뒤집어서 보겠다는 뜻. 
arr

array([ 0.9560996 ,  0.90699913,  0.82006522,  0.61399681,  0.49654601,
        0.42606694,  0.4142223 ,  0.26652212,  0.12953234,  0.00316708])

### 실습 2-2 백터를 행렬로 변환하기
길이 9의 벡터(1차원 배열)를 생성하고 이를 3x3 크기의 행렬로 변환

In [4]:
import numpy
arr = numpy.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr = numpy.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 실습 2-3 대각행렬
실습 2-2에서 생성한 행렬을 대각행렬로 변환

In [6]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
# 행렬의 주대각 원소(대각선상에 있는 원소)만 1차원 배열로 출력
diag = numpy.diag(arr)
diag

array([0, 4, 8])

In [10]:
# 3x3 대각행렬로 변환
diag_mat = numpy.diag(numpy.diag(arr))
diag_mat

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

### 실습 2-4 행렬 정규화
정수로 이루어진 5x5 행렬을 만들고 정규화

In [11]:
#randint()함수를 이용해 1부터 100 사이의 임의의 정수로 이루어진 행렬을 생성
import numpy
arr = numpy.random.randint(1,100, size =(5,5))
arr

array([[97, 39, 41, 66, 71],
       [84, 54, 61, 16, 10],
       [52, 31,  6, 18, 90],
       [99, 34, 86, 16, 96],
       [80,  6,  4, 12, 13]])

In [15]:
#행렬 내의 값들을 정규화
arrMax, arrMin = arr.max(), arr.min()
arr_normalized = (arr - arrMin)/(arrMax - arrMin)
arr_normalized

array([[ 0.97894737,  0.36842105,  0.38947368,  0.65263158,  0.70526316],
       [ 0.84210526,  0.52631579,  0.6       ,  0.12631579,  0.06315789],
       [ 0.50526316,  0.28421053,  0.02105263,  0.14736842,  0.90526316],
       [ 1.        ,  0.31578947,  0.86315789,  0.12631579,  0.96842105],
       [ 0.8       ,  0.02105263,  0.        ,  0.08421053,  0.09473684]])

### 실습 2-5 행렬 곱

In [16]:
import numpy
A = numpy.array([[1,2,3],[4,5,6]])
A #2x3 배열

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
B = numpy.array([[1,2,],[3,4],[5,6]])
B #3x2 배열

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
result = numpy.dot(A,B)
result

array([[22, 28],
       [49, 64]])

### 실습 2-6 주식 데이터 불러오기 

In [19]:
import numpy
data = numpy.loadtxt('data/stock-data.csv',delimiter = ',')
data

array([[  8.28659973e+02,   8.33450012e+02,   8.28349976e+02,
          1.24770000e+06,   8.31659973e+02],
       [  8.23020020e+02,   8.28070007e+02,   8.21655029e+02,
          1.59780000e+06,   8.28070007e+02],
       [  8.19929993e+02,   8.24400024e+02,   8.18979980e+02,
          1.28170000e+06,   8.24159973e+02],
       ..., 
       [  5.66892592e+02,   5.67002574e+02,   5.56932537e+02,
          1.08000000e+04,   5.56972503e+02],
       [  5.61202549e+02,   5.66432590e+02,   5.58672539e+02,
          4.12000000e+04,   5.59992565e+02],
       [  5.68002570e+02,   5.68002570e+02,   5.52922516e+02,
          1.31000000e+04,   5.58462551e+02]])

In [20]:
#1열부터 4열('Open','High','Low','Volume')까지의 데이터는 x_data로 저장하고 
#5열('Close')의 데이터는 y_data로 저장
x_data = data[: , : -1]    # :-1의 뜻 / 마지막 열 빼고 
x_data

array([[  8.28659973e+02,   8.33450012e+02,   8.28349976e+02,
          1.24770000e+06],
       [  8.23020020e+02,   8.28070007e+02,   8.21655029e+02,
          1.59780000e+06],
       [  8.19929993e+02,   8.24400024e+02,   8.18979980e+02,
          1.28170000e+06],
       ..., 
       [  5.66892592e+02,   5.67002574e+02,   5.56932537e+02,
          1.08000000e+04],
       [  5.61202549e+02,   5.66432590e+02,   5.58672539e+02,
          4.12000000e+04],
       [  5.68002570e+02,   5.68002570e+02,   5.52922516e+02,
          1.31000000e+04]])

In [21]:
x_data.shape

(732, 4)

In [22]:
y_data = data[: , -1] #-1의 뜻 / 마지막 열만
y_data

array([ 831.659973,  828.070007,  824.159973,  818.97998 ,  820.450012,
        819.23999 ,  813.669983,  809.559998,  808.380005,  806.969971,
        801.340027,  801.48999 ,  798.530029,  795.695007,  796.789978,
        802.320007,  823.309998,  832.150024,  835.669983,  823.869995,
        819.309998,  805.02002 ,  802.174988,  806.070007,  804.609985,
        807.880005,  806.359985,  807.909973,  804.789978,  806.650024,
        806.150024,  794.02002 ,  786.900024,  786.140015,  771.820007,
        782.789978,  785.049988,  791.549988,  789.909973,  791.26001 ,
        794.559998,  796.419983,  794.200012,  790.799988,  797.849976,
        797.070007,  796.099976,  789.27002 ,  789.289978,  776.419983,
        771.190002,  759.109985,  762.52002 ,  750.5     ,  747.919983,
        758.039978,  770.840027,  768.23999 ,  761.679993,  760.98999 ,
        768.27002 ,  769.200012,  760.539978,  771.22998 ,  764.47998 ,
        758.48999 ,  736.080017,  754.02002 ,  762.559998,  785.

In [23]:
y_data.shape

(732,)

### 실습 2-7 당뇨 데이터 불러오기

In [24]:
data = numpy.loadtxt('data/diabetes-data.csv',delimiter = ',')
data

array([[-0.294118 ,  0.487437 ,  0.180328 , ..., -0.53117  , -0.0333333,
         0.       ],
       [-0.882353 , -0.145729 ,  0.0819672, ..., -0.766866 , -0.666667 ,
         1.       ],
       [-0.0588235,  0.839196 ,  0.0491803, ..., -0.492741 , -0.633333 ,
         0.       ],
       ..., 
       [-0.411765 ,  0.21608  ,  0.180328 , ..., -0.857387 , -0.7      ,
         1.       ],
       [-0.882353 ,  0.266332 , -0.0163934, ..., -0.768574 , -0.133333 ,
         0.       ],
       [-0.882353 , -0.0653266,  0.147541 , ..., -0.797609 , -0.933333 ,
         1.       ]])

In [25]:
#1열부터 8열까지의 데이터는 x_data로 저장하고 9열의 데이터는 y_data로 저장
x_data = data[: , :-1]
x_data

array([[-0.294118  ,  0.487437  ,  0.180328  , ...,  0.00149028,
        -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , ..., -0.207153  ,
        -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 , ..., -0.305514  ,
        -0.492741  , -0.633333  ],
       ..., 
       [-0.411765  ,  0.21608   ,  0.180328  , ..., -0.219076  ,
        -0.857387  , -0.7       ],
       [-0.882353  ,  0.266332  , -0.0163934 , ..., -0.102832  ,
        -0.768574  , -0.133333  ],
       [-0.882353  , -0.0653266 ,  0.147541  , ..., -0.0938897 ,
        -0.797609  , -0.933333  ]])

In [26]:
x_data.shape

(759, 8)

In [27]:
y_data = data[: , -1]
y_data

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1

In [28]:
y_data.shape

(759,)